# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Software testing build demo

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present

    - name: Run npm test
      run: |
        npm install
        npm test 
      continue-on-error: true
    
    - name: Run coverage report
      run: |
        npm install
        npm run coveralls
      continue-on-error: true
      
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ github.token }}
